USE diploma;
CREATE TABLE IF NOT EXISTS USERS (ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(100),ROLE VARCHAR(15) NOT NULL,LOGIN VARCHAR(100) NOT NULL,PASSWORD VARCHAR(100) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Situation(ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(30), DESCRIPTION VARCHAR(500) ,PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS METRICS(ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(20),VALUE DOUBLE,SITUATION_ID INT,PRIMARY KEY (ID),FOREIGN KEY (SITUATION_ID) REFERENCES Situation(ID));
CREATE TABLE IF NOT EXISTS RECORDS(ID INT NOT NULL AUTO_INCREMENT,USER_ID INT NOT NULL ,DATE DATETIME,SITUATION_ID INT NOT NULL , PLAIN_ID INT NOT NULL,SIM_DATA TEXT,PRIMARY KEY (ID),FOREIGN KEY (USER_ID) REFERENCES USERS(ID), FOREIGN KEY (SITUATION_ID) REFERENCES Situation(ID), FOREIGN KEY (PLAIN_ID) REFERENCES PLAINS(ID));
CREATE TABLE IF NOT EXISTS PLAINS(ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(30) UNIQUE, PRIMARY KEY (ID));
