USE diploma;
CREATE TABLE IF NOT EXISTS USERS (ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(100),ROLE VARCHAR(15) NOT NULL,LOGIN VARCHAR(100) NOT NULL,PASSWORD VARCHAR(100) NOT NULL,PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS PLAIN_MODELS(ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(30) UNIQUE ,PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS METRICS(ID INT NOT NULL AUTO_INCREMENT,NAME VARCHAR(20),VALUE DOUBLE,PLAIN_MODEL_ID INT,PRIMARY KEY (ID),FOREIGN KEY (PLAIN_MODEL_ID) REFERENCES PLAIN_MODELS(ID));
CREATE TABLE IF NOT EXISTS RECORDS(ID INT NOT NULL AUTO_INCREMENT,USER_ID INT NOT NULL ,DATE DATETIME,PLAIN_MODEL_ID INT NOT NULL ,SIM_DATA TEXT,PRIMARY KEY (ID),FOREIGN KEY (USER_ID) REFERENCES USERS(ID), FOREIGN KEY (PLAIN_MODEL_ID) REFERENCES PLAIN_MODELS(ID));


